### ISSUE TITLE
Misleading explanation for why python doess not require variable declarations

### ISSUE THREAD

**Issue by siellsiell** [HumbleData/beginners-data-workshop#8]
Hi!

I'm one of the mentors and while looking through the first notebook, I saw this explanation: "Python is an object oriented programming language. You do not need to declare variables (or their types) before using them as every variable in python is an object."

I don't think that's quite true. You do not need to declare variables or their types because Python is a dynamically typed language, not because it is object oriented. Java is object oriented and yet Java requires variable declarations with types. Maybe the confusion comes from this fact: Python has types; however, the types are linked not to the variable names but to the objects themselves (but this is not the case in Java, which is also object oriented).

**Comment by SandrineP** [comment]
Hey,
Thanks! Do you have an idea of a sentence that would explain that easily (thinking about people who are new to coding)?
Btw, feel free to clone the repo and suggest any change you think are relevant to improve the workshop!
