### ISSUE TITLE
Using Colab instead of Jupyter Notebooks

### ISSUE THREAD

**Issue by abdulelahsm** [HumbleData/beginners-data-workshop#9]
In the past workshops I've run for beginners, Colab is way easier for beginners to get started with. The most difficult part those workshops was setting up the environment/conda.

I suggest you consider colab as an option

**Comment by john-sandall** [comment]
We agree, Colab is good, but https://cocalc.com/ is better given the shared kernel environment. It can get pricey though as numbers grow, we'll be looking at their open sourced version as well as things like https://deepnote.com/ to bring down costs as the project grows.
